### ISSUE TITLE
Item Name Cropping

### ISSUE THREAD

**Issue by saichaitanyaeruvaram** [anupam42/PG-DAPP#69]
We have to give user the choice to enter the shortcut of the item. We can auto-fill, but user should be able to override.
Currently we are displaying first n characters.

![item_name](https://cloud.githubusercontent.com/assets/10721851/17123314/645b98ee-5300-11e6-8ee7-5588d29048f7.png)

**Comment by moghribalakrishna** [comment]
Discuss this in Detail with Sahi.

**Comment by samurailens** [comment]
@anupam42 : I see some formatting issues in the screenshot provided. 

Please see the 'Total' column ... the value is like $120.00000000 ... Can we just have $120.22 ? instead of so many zeros.. This total field is everywhere like that. In the above screenshot, see bottom left corner for total .. there also, this format is there. 

Please change it with this issue itself.

**Comment by samurailens** [comment]
verified. Issue not present now.

Re-open if needed.
